name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Install HLint
        uses: haskell-actions/hlint-setup@v2

      - name: Run HLint
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["src/", "app/", "test/"]'
          fail-on: suggestion

      - name: Build
        run: stack build --fast

      - name: Test
        run: stack test --fast
